# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - pagemaster

# pagemaster plugin:
# $ 'bundle exec jekyll articles' // creates .md pages in the collection _articles
# $ 'bundle exec jekyll pages' // creates .md pages in the collection _articles (This collection contains the pages from which the main navigation is auto-generated from.)
collections:
  sections:
    output: true
    source: sections.csv
    id_key: pid
    layout: section
  articles:
    output: true
    source: articles.csv
    id_key: pid
    layout: article

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - update_boostrap.sh
