title: Fancy Title
author: Fancy Pants
email: "example@example.com"
description: This is a fancy example description which can be edited in the _data/config.yml file
#twitter_username: fancy
#github_username:  fancy
#facebook_username:  fancy
#instagram_username:  fancy
